/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.usersnotifications.view;

/**
 *
 * @author logcomex
 */
public class MainWindowView extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public MainWindowView() {
        super("Notificações do usuários");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        notificationMenu = new javax.swing.JMenu();
        sendNotificationMenuItem = new javax.swing.JMenuItem();
        viewNotificationMenuItem = new javax.swing.JMenuItem();
        managerAccountMenu = new javax.swing.JMenu();
        changePassordMenuItem = new javax.swing.JMenuItem();
        managerMenu = new javax.swing.JMenu();
        usersAuthorizedMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        notificationMenu.setMnemonic('e');
        notificationMenu.setText("Notificações");

        sendNotificationMenuItem.setMnemonic('t');
        sendNotificationMenuItem.setText("Enviar Notificação");
        sendNotificationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNotificationMenuItemActionPerformed(evt);
            }
        });
        notificationMenu.add(sendNotificationMenuItem);

        viewNotificationMenuItem.setMnemonic('y');
        viewNotificationMenuItem.setText("Visualizar notificações");
        notificationMenu.add(viewNotificationMenuItem);

        menuBar.add(notificationMenu);

        managerAccountMenu.setMnemonic('h');
        managerAccountMenu.setText("Gestão de conta");

        changePassordMenuItem.setMnemonic('a');
        changePassordMenuItem.setText("Alterar senha");
        managerAccountMenu.add(changePassordMenuItem);

        menuBar.add(managerAccountMenu);

        managerMenu.setMnemonic('h');
        managerMenu.setText("Gestão de usuários");

        usersAuthorizedMenuItem.setText("Autorizar usuários");
        managerMenu.add(usersAuthorizedMenuItem);

        menuBar.add(managerMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1197, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendNotificationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sendNotificationMenuItemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_sendNotificationMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindowView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem changePassordMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu managerAccountMenu;
    private javax.swing.JMenu managerMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu notificationMenu;
    private javax.swing.JMenuItem sendNotificationMenuItem;
    private javax.swing.JMenuItem usersAuthorizedMenuItem;
    private javax.swing.JMenuItem viewNotificationMenuItem;
    // End of variables declaration//GEN-END:variables

}
